export const CURRENCY_ARRAY: {
	name: string;
	symbol: string;
	symbolNative: string;
	minorUnits: number;
	rounding: number;
	code: string;
	namePlural: string;
}[] = [
	{
		name: "US Dollar",
		symbol: "$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "USD",
		namePlural: "US dollars",
	},
	{
		name: "Canadian Dollar",
		symbol: "CA$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "CAD",
		namePlural: "Canadian dollars",
	},
	{
		name: "Euro",
		symbol: "€",
		symbolNative: "€",
		minorUnits: 2,
		rounding: 0,
		code: "EUR",
		namePlural: "euros",
	},
	{
		name: "United Arab Emirates Dirham",
		symbol: "AED",
		symbolNative: "د.إ.‏",
		minorUnits: 2,
		rounding: 0,
		code: "AED",
		namePlural: "UAE dirhams",
	},
	{
		name: "Afghan Afghani",
		symbol: "Af",
		symbolNative: "؋",
		minorUnits: 0,
		rounding: 0,
		code: "AFN",
		namePlural: "Afghan Afghanis",
	},
	{
		name: "Albanian Lek",
		symbol: "ALL",
		symbolNative: "Lek",
		minorUnits: 0,
		rounding: 0,
		code: "ALL",
		namePlural: "Albanian lekë",
	},
	{
		name: "Armenian Dram",
		symbol: "AMD",
		symbolNative: "դր.",
		minorUnits: 0,
		rounding: 0,
		code: "AMD",
		namePlural: "Armenian drams",
	},
	{
		name: "Argentine Peso",
		symbol: "AR$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "ARS",
		namePlural: "Argentine pesos",
	},
	{
		name: "Australian Dollar",
		symbol: "AU$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "AUD",
		namePlural: "Australian dollars",
	},
	{
		name: "Azerbaijani Manat",
		symbol: "man.",
		symbolNative: "ман.",
		minorUnits: 2,
		rounding: 0,
		code: "AZN",
		namePlural: "Azerbaijani manats",
	},
	{
		name: "Bosnia-Herzegovina Convertible Mark",
		symbol: "KM",
		symbolNative: "KM",
		minorUnits: 2,
		rounding: 0,
		code: "BAM",
		namePlural: "Bosnia-Herzegovina convertible marks",
	},
	{
		name: "Bangladeshi Taka",
		symbol: "Tk",
		symbolNative: "৳",
		minorUnits: 2,
		rounding: 0,
		code: "BDT",
		namePlural: "Bangladeshi takas",
	},
	{
		name: "Bulgarian Lev",
		symbol: "BGN",
		symbolNative: "лв.",
		minorUnits: 2,
		rounding: 0,
		code: "BGN",
		namePlural: "Bulgarian leva",
	},
	{
		name: "Bahraini Dinar",
		symbol: "BD",
		symbolNative: "د.ب.‏",
		minorUnits: 3,
		rounding: 0,
		code: "BHD",
		namePlural: "Bahraini dinars",
	},
	{
		name: "Burundian Franc",
		symbol: "FBu",
		symbolNative: "FBu",
		minorUnits: 0,
		rounding: 0,
		code: "BIF",
		namePlural: "Burundian francs",
	},
	{
		name: "Brunei Dollar",
		symbol: "BN$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "BND",
		namePlural: "Brunei dollars",
	},
	{
		name: "Bolivian Boliviano",
		symbol: "Bs",
		symbolNative: "Bs",
		minorUnits: 2,
		rounding: 0,
		code: "BOB",
		namePlural: "Bolivian bolivianos",
	},
	{
		name: "Brazilian Real",
		symbol: "R$",
		symbolNative: "R$",
		minorUnits: 2,
		rounding: 0,
		code: "BRL",
		namePlural: "Brazilian reals",
	},
	{
		name: "Botswanan Pula",
		symbol: "BWP",
		symbolNative: "P",
		minorUnits: 2,
		rounding: 0,
		code: "BWP",
		namePlural: "Botswanan pulas",
	},
	{
		name: "Belarusian Ruble",
		symbol: "Br",
		symbolNative: "руб.",
		minorUnits: 2,
		rounding: 0,
		code: "BYN",
		namePlural: "Belarusian rubles",
	},
	{
		name: "Belize Dollar",
		symbol: "BZ$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "BZD",
		namePlural: "Belize dollars",
	},
	{
		name: "Congolese Franc",
		symbol: "CDF",
		symbolNative: "FrCD",
		minorUnits: 2,
		rounding: 0,
		code: "CDF",
		namePlural: "Congolese francs",
	},
	{
		name: "Swiss Franc",
		symbol: "CHF",
		symbolNative: "CHF",
		minorUnits: 2,
		rounding: 0.05,
		code: "CHF",
		namePlural: "Swiss francs",
	},
	{
		name: "Chilean Peso",
		symbol: "CL$",
		symbolNative: "$",
		minorUnits: 0,
		rounding: 0,
		code: "CLP",
		namePlural: "Chilean pesos",
	},
	{
		name: "Chinese Yuan",
		symbol: "CN¥",
		symbolNative: "CN¥",
		minorUnits: 2,
		rounding: 0,
		code: "CNY",
		namePlural: "Chinese yuan",
	},
	{
		name: "Colombian Peso",
		symbol: "CO$",
		symbolNative: "$",
		minorUnits: 0,
		rounding: 0,
		code: "COP",
		namePlural: "Colombian pesos",
	},
	{
		name: "Costa Rican Colón",
		symbol: "₡",
		symbolNative: "₡",
		minorUnits: 0,
		rounding: 0,
		code: "CRC",
		namePlural: "Costa Rican colóns",
	},
	{
		name: "Cape Verdean Escudo",
		symbol: "CV$",
		symbolNative: "CV$",
		minorUnits: 2,
		rounding: 0,
		code: "CVE",
		namePlural: "Cape Verdean escudos",
	},
	{
		name: "Czech Republic Koruna",
		symbol: "Kč",
		symbolNative: "Kč",
		minorUnits: 2,
		rounding: 0,
		code: "CZK",
		namePlural: "Czech Republic korunas",
	},
	{
		name: "Djiboutian Franc",
		symbol: "Fdj",
		symbolNative: "Fdj",
		minorUnits: 0,
		rounding: 0,
		code: "DJF",
		namePlural: "Djiboutian francs",
	},
	{
		name: "Danish Krone",
		symbol: "Dkr",
		symbolNative: "kr",
		minorUnits: 2,
		rounding: 0,
		code: "DKK",
		namePlural: "Danish kroner",
	},
	{
		name: "Dominican Peso",
		symbol: "RD$",
		symbolNative: "RD$",
		minorUnits: 2,
		rounding: 0,
		code: "DOP",
		namePlural: "Dominican pesos",
	},
	{
		name: "Algerian Dinar",
		symbol: "DA",
		symbolNative: "د.ج.‏",
		minorUnits: 2,
		rounding: 0,
		code: "DZD",
		namePlural: "Algerian dinars",
	},
	{
		name: "Estonian Kroon",
		symbol: "Ekr",
		symbolNative: "kr",
		minorUnits: 2,
		rounding: 0,
		code: "EEK",
		namePlural: "Estonian kroons",
	},
	{
		name: "Egyptian Pound",
		symbol: "EGP",
		symbolNative: "ج.م.‏",
		minorUnits: 2,
		rounding: 0,
		code: "EGP",
		namePlural: "Egyptian pounds",
	},
	{
		name: "Eritrean Nakfa",
		symbol: "Nfk",
		symbolNative: "Nfk",
		minorUnits: 2,
		rounding: 0,
		code: "ERN",
		namePlural: "Eritrean nakfas",
	},
	{
		name: "Ethiopian Birr",
		symbol: "Br",
		symbolNative: "Br",
		minorUnits: 2,
		rounding: 0,
		code: "ETB",
		namePlural: "Ethiopian birrs",
	},
	{
		name: "British Pound Sterling",
		symbol: "£",
		symbolNative: "£",
		minorUnits: 2,
		rounding: 0,
		code: "GBP",
		namePlural: "British pounds sterling",
	},
	{
		name: "Georgian Lari",
		symbol: "GEL",
		symbolNative: "GEL",
		minorUnits: 2,
		rounding: 0,
		code: "GEL",
		namePlural: "Georgian laris",
	},
	{
		name: "Ghanaian Cedi",
		symbol: "GH₵",
		symbolNative: "GH₵",
		minorUnits: 2,
		rounding: 0,
		code: "GHS",
		namePlural: "Ghanaian cedis",
	},
	{
		name: "Guinean Franc",
		symbol: "FG",
		symbolNative: "FG",
		minorUnits: 0,
		rounding: 0,
		code: "GNF",
		namePlural: "Guinean francs",
	},
	{
		name: "Guatemalan Quetzal",
		symbol: "GTQ",
		symbolNative: "Q",
		minorUnits: 2,
		rounding: 0,
		code: "GTQ",
		namePlural: "Guatemalan quetzals",
	},
	{
		name: "Hong Kong Dollar",
		symbol: "HK$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "HKD",
		namePlural: "Hong Kong dollars",
	},
	{
		name: "Honduran Lempira",
		symbol: "HNL",
		symbolNative: "L",
		minorUnits: 2,
		rounding: 0,
		code: "HNL",
		namePlural: "Honduran lempiras",
	},
	{
		name: "Croatian Kuna",
		symbol: "kn",
		symbolNative: "kn",
		minorUnits: 2,
		rounding: 0,
		code: "HRK",
		namePlural: "Croatian kunas",
	},
	{
		name: "Hungarian Forint",
		symbol: "Ft",
		symbolNative: "Ft",
		minorUnits: 0,
		rounding: 0,
		code: "HUF",
		namePlural: "Hungarian forints",
	},
	{
		name: "Indonesian Rupiah",
		symbol: "Rp",
		symbolNative: "Rp",
		minorUnits: 0,
		rounding: 0,
		code: "IDR",
		namePlural: "Indonesian rupiahs",
	},
	{
		name: "Israeli New Sheqel",
		symbol: "₪",
		symbolNative: "₪",
		minorUnits: 2,
		rounding: 0,
		code: "ILS",
		namePlural: "Israeli new sheqels",
	},
	{
		name: "Indian Rupee",
		symbol: "₹",
		symbolNative: "টকা",
		minorUnits: 2,
		rounding: 0,
		code: "INR",
		namePlural: "Indian rupees",
	},
	{
		name: "Iraqi Dinar",
		symbol: "IQD",
		symbolNative: "د.ع.‏",
		minorUnits: 0,
		rounding: 0,
		code: "IQD",
		namePlural: "Iraqi dinars",
	},
	{
		name: "Iranian Rial",
		symbol: "IRR",
		symbolNative: "﷼",
		minorUnits: 0,
		rounding: 0,
		code: "IRR",
		namePlural: "Iranian rials",
	},
	{
		name: "Icelandic Króna",
		symbol: "Ikr",
		symbolNative: "kr",
		minorUnits: 0,
		rounding: 0,
		code: "ISK",
		namePlural: "Icelandic krónur",
	},
	{
		name: "Jamaican Dollar",
		symbol: "J$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "JMD",
		namePlural: "Jamaican dollars",
	},
	{
		name: "Jordanian Dinar",
		symbol: "JD",
		symbolNative: "د.أ.‏",
		minorUnits: 3,
		rounding: 0,
		code: "JOD",
		namePlural: "Jordanian dinars",
	},
	{
		name: "Japanese Yen",
		symbol: "¥",
		symbolNative: "￥",
		minorUnits: 0,
		rounding: 0,
		code: "JPY",
		namePlural: "Japanese yen",
	},
	{
		name: "Kenyan Shilling",
		symbol: "Ksh",
		symbolNative: "Ksh",
		minorUnits: 2,
		rounding: 0,
		code: "KES",
		namePlural: "Kenyan shillings",
	},
	{
		name: "Cambodian Riel",
		symbol: "KHR",
		symbolNative: "៛",
		minorUnits: 2,
		rounding: 0,
		code: "KHR",
		namePlural: "Cambodian riels",
	},
	{
		name: "Comorian Franc",
		symbol: "CF",
		symbolNative: "FC",
		minorUnits: 0,
		rounding: 0,
		code: "KMF",
		namePlural: "Comorian francs",
	},
	{
		name: "South Korean Won",
		symbol: "₩",
		symbolNative: "₩",
		minorUnits: 0,
		rounding: 0,
		code: "KRW",
		namePlural: "South Korean won",
	},
	{
		name: "Kuwaiti Dinar",
		symbol: "KD",
		symbolNative: "د.ك.‏",
		minorUnits: 3,
		rounding: 0,
		code: "KWD",
		namePlural: "Kuwaiti dinars",
	},
	{
		name: "Kazakhstani Tenge",
		symbol: "KZT",
		symbolNative: "тңг.",
		minorUnits: 2,
		rounding: 0,
		code: "KZT",
		namePlural: "Kazakhstani tenges",
	},
	{
		name: "Lebanese Pound",
		symbol: "LB£",
		symbolNative: "ل.ل.‏",
		minorUnits: 0,
		rounding: 0,
		code: "LBP",
		namePlural: "Lebanese pounds",
	},
	{
		name: "Sri Lankan Rupee",
		symbol: "SLRs",
		symbolNative: "SL Re",
		minorUnits: 2,
		rounding: 0,
		code: "LKR",
		namePlural: "Sri Lankan rupees",
	},
	{
		name: "Lithuanian Litas",
		symbol: "Lt",
		symbolNative: "Lt",
		minorUnits: 2,
		rounding: 0,
		code: "LTL",
		namePlural: "Lithuanian litai",
	},
	{
		name: "Latvian Lats",
		symbol: "Ls",
		symbolNative: "Ls",
		minorUnits: 2,
		rounding: 0,
		code: "LVL",
		namePlural: "Latvian lati",
	},
	{
		name: "Libyan Dinar",
		symbol: "LD",
		symbolNative: "د.ل.‏",
		minorUnits: 3,
		rounding: 0,
		code: "LYD",
		namePlural: "Libyan dinars",
	},
	{
		name: "Moroccan Dirham",
		symbol: "MAD",
		symbolNative: "د.م.‏",
		minorUnits: 2,
		rounding: 0,
		code: "MAD",
		namePlural: "Moroccan dirhams",
	},
	{
		name: "Moldovan Leu",
		symbol: "MDL",
		symbolNative: "MDL",
		minorUnits: 2,
		rounding: 0,
		code: "MDL",
		namePlural: "Moldovan lei",
	},
	{
		name: "Malagasy Ariary",
		symbol: "MGA",
		symbolNative: "MGA",
		minorUnits: 0,
		rounding: 0,
		code: "MGA",
		namePlural: "Malagasy Ariaries",
	},
	{
		name: "Macedonian Denar",
		symbol: "MKD",
		symbolNative: "MKD",
		minorUnits: 2,
		rounding: 0,
		code: "MKD",
		namePlural: "Macedonian denari",
	},
	{
		name: "Myanma Kyat",
		symbol: "MMK",
		symbolNative: "K",
		minorUnits: 0,
		rounding: 0,
		code: "MMK",
		namePlural: "Myanma kyats",
	},
	{
		name: "Macanese Pataca",
		symbol: "MOP$",
		symbolNative: "MOP$",
		minorUnits: 2,
		rounding: 0,
		code: "MOP",
		namePlural: "Macanese patacas",
	},
	{
		name: "Mauritian Rupee",
		symbol: "MURs",
		symbolNative: "MURs",
		minorUnits: 0,
		rounding: 0,
		code: "MUR",
		namePlural: "Mauritian rupees",
	},
	{
		name: "Mexican Peso",
		symbol: "MX$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "MXN",
		namePlural: "Mexican pesos",
	},
	{
		name: "Malaysian Ringgit",
		symbol: "RM",
		symbolNative: "RM",
		minorUnits: 2,
		rounding: 0,
		code: "MYR",
		namePlural: "Malaysian ringgits",
	},
	{
		name: "Mozambican Metical",
		symbol: "MTn",
		symbolNative: "MTn",
		minorUnits: 2,
		rounding: 0,
		code: "MZN",
		namePlural: "Mozambican meticals",
	},
	{
		name: "Namibian Dollar",
		symbol: "N$",
		symbolNative: "N$",
		minorUnits: 2,
		rounding: 0,
		code: "NAD",
		namePlural: "Namibian dollars",
	},
	{
		name: "Nigerian Naira",
		symbol: "₦",
		symbolNative: "₦",
		minorUnits: 2,
		rounding: 0,
		code: "NGN",
		namePlural: "Nigerian nairas",
	},
	{
		name: "Nicaraguan Córdoba",
		symbol: "C$",
		symbolNative: "C$",
		minorUnits: 2,
		rounding: 0,
		code: "NIO",
		namePlural: "Nicaraguan córdobas",
	},
	{
		name: "Norwegian Krone",
		symbol: "Nkr",
		symbolNative: "kr",
		minorUnits: 2,
		rounding: 0,
		code: "NOK",
		namePlural: "Norwegian kroner",
	},
	{
		name: "Nepalese Rupee",
		symbol: "NPRs",
		symbolNative: "नेरू",
		minorUnits: 2,
		rounding: 0,
		code: "NPR",
		namePlural: "Nepalese rupees",
	},
	{
		name: "New Zealand Dollar",
		symbol: "NZ$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "NZD",
		namePlural: "New Zealand dollars",
	},
	{
		name: "Omani Rial",
		symbol: "OMR",
		symbolNative: "ر.ع.‏",
		minorUnits: 3,
		rounding: 0,
		code: "OMR",
		namePlural: "Omani rials",
	},
	{
		name: "Panamanian Balboa",
		symbol: "B/.",
		symbolNative: "B/.",
		minorUnits: 2,
		rounding: 0,
		code: "PAB",
		namePlural: "Panamanian balboas",
	},
	{
		name: "Peruvian Nuevo Sol",
		symbol: "S/.",
		symbolNative: "S/.",
		minorUnits: 2,
		rounding: 0,
		code: "PEN",
		namePlural: "Peruvian nuevos soles",
	},
	{
		name: "Philippine Peso",
		symbol: "₱",
		symbolNative: "₱",
		minorUnits: 2,
		rounding: 0,
		code: "PHP",
		namePlural: "Philippine pesos",
	},
	{
		name: "Pakistani Rupee",
		symbol: "PKRs",
		symbolNative: "₨",
		minorUnits: 0,
		rounding: 0,
		code: "PKR",
		namePlural: "Pakistani rupees",
	},
	{
		name: "Polish Zloty",
		symbol: "zł",
		symbolNative: "zł",
		minorUnits: 2,
		rounding: 0,
		code: "PLN",
		namePlural: "Polish zlotys",
	},
	{
		name: "Paraguayan Guarani",
		symbol: "₲",
		symbolNative: "₲",
		minorUnits: 0,
		rounding: 0,
		code: "PYG",
		namePlural: "Paraguayan guaranis",
	},
	{
		name: "Qatari Rial",
		symbol: "QR",
		symbolNative: "ر.ق.‏",
		minorUnits: 2,
		rounding: 0,
		code: "QAR",
		namePlural: "Qatari rials",
	},
	{
		name: "Romanian Leu",
		symbol: "RON",
		symbolNative: "RON",
		minorUnits: 2,
		rounding: 0,
		code: "RON",
		namePlural: "Romanian lei",
	},
	{
		name: "Serbian Dinar",
		symbol: "din.",
		symbolNative: "дин.",
		minorUnits: 0,
		rounding: 0,
		code: "RSD",
		namePlural: "Serbian dinars",
	},
	{
		name: "Russian Ruble",
		symbol: "RUB",
		symbolNative: "₽.",
		minorUnits: 2,
		rounding: 0,
		code: "RUB",
		namePlural: "Russian rubles",
	},
	{
		name: "Rwandan Franc",
		symbol: "RWF",
		symbolNative: "FR",
		minorUnits: 0,
		rounding: 0,
		code: "RWF",
		namePlural: "Rwandan francs",
	},
	{
		name: "Saudi Riyal",
		symbol: "SR",
		symbolNative: "ر.س.‏",
		minorUnits: 2,
		rounding: 0,
		code: "SAR",
		namePlural: "Saudi riyals",
	},
	{
		name: "Sudanese Pound",
		symbol: "SDG",
		symbolNative: "SDG",
		minorUnits: 2,
		rounding: 0,
		code: "SDG",
		namePlural: "Sudanese pounds",
	},
	{
		name: "Swedish Krona",
		symbol: "Skr",
		symbolNative: "kr",
		minorUnits: 2,
		rounding: 0,
		code: "SEK",
		namePlural: "Swedish kronor",
	},
	{
		name: "Singapore Dollar",
		symbol: "S$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "SGD",
		namePlural: "Singapore dollars",
	},
	{
		name: "Somali Shilling",
		symbol: "Ssh",
		symbolNative: "Ssh",
		minorUnits: 0,
		rounding: 0,
		code: "SOS",
		namePlural: "Somali shillings",
	},
	{
		name: "Syrian Pound",
		symbol: "SY£",
		symbolNative: "ل.س.‏",
		minorUnits: 0,
		rounding: 0,
		code: "SYP",
		namePlural: "Syrian pounds",
	},
	{
		name: "Thai Baht",
		symbol: "฿",
		symbolNative: "฿",
		minorUnits: 2,
		rounding: 0,
		code: "THB",
		namePlural: "Thai baht",
	},
	{
		name: "Tunisian Dinar",
		symbol: "DT",
		symbolNative: "د.ت.‏",
		minorUnits: 3,
		rounding: 0,
		code: "TND",
		namePlural: "Tunisian dinars",
	},
	{
		name: "Tongan Paʻanga",
		symbol: "T$",
		symbolNative: "T$",
		minorUnits: 2,
		rounding: 0,
		code: "TOP",
		namePlural: "Tongan paʻanga",
	},
	{
		name: "Turkish Lira",
		symbol: "TL",
		symbolNative: "TL",
		minorUnits: 2,
		rounding: 0,
		code: "TRY",
		namePlural: "Turkish Lira",
	},
	{
		name: "Trinidad and Tobago Dollar",
		symbol: "TT$",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "TTD",
		namePlural: "Trinidad and Tobago dollars",
	},
	{
		name: "New Taiwan Dollar",
		symbol: "NT$",
		symbolNative: "NT$",
		minorUnits: 2,
		rounding: 0,
		code: "TWD",
		namePlural: "New Taiwan dollars",
	},
	{
		name: "Tanzanian Shilling",
		symbol: "TSh",
		symbolNative: "TSh",
		minorUnits: 0,
		rounding: 0,
		code: "TZS",
		namePlural: "Tanzanian shillings",
	},
	{
		name: "Ukrainian Hryvnia",
		symbol: "₴",
		symbolNative: "₴",
		minorUnits: 2,
		rounding: 0,
		code: "UAH",
		namePlural: "Ukrainian hryvnias",
	},
	{
		name: "Ugandan Shilling",
		symbol: "USh",
		symbolNative: "USh",
		minorUnits: 0,
		rounding: 0,
		code: "UGX",
		namePlural: "Ugandan shillings",
	},
	{
		name: "Uruguayan Peso",
		symbol: "$U",
		symbolNative: "$",
		minorUnits: 2,
		rounding: 0,
		code: "UYU",
		namePlural: "Uruguayan pesos",
	},
	{
		name: "Uzbekistan Som",
		symbol: "UZS",
		symbolNative: "UZS",
		minorUnits: 0,
		rounding: 0,
		code: "UZS",
		namePlural: "Uzbekistan som",
	},
	{
		name: "Venezuelan Bolívar",
		symbol: "Bs.F.",
		symbolNative: "Bs.F.",
		minorUnits: 2,
		rounding: 0,
		code: "VEF",
		namePlural: "Venezuelan bolívars",
	},
	{
		name: "Vietnamese Dong",
		symbol: "₫",
		symbolNative: "₫",
		minorUnits: 0,
		rounding: 0,
		code: "VND",
		namePlural: "Vietnamese dong",
	},
	{
		name: "CFA Franc BEAC",
		symbol: "FCFA",
		symbolNative: "FCFA",
		minorUnits: 0,
		rounding: 0,
		code: "XAF",
		namePlural: "CFA francs BEAC",
	},
	{
		name: "CFA Franc BCEAO",
		symbol: "CFA",
		symbolNative: "CFA",
		minorUnits: 0,
		rounding: 0,
		code: "XOF",
		namePlural: "CFA francs BCEAO",
	},
	{
		name: "Yemeni Rial",
		symbol: "YR",
		symbolNative: "ر.ي.‏",
		minorUnits: 0,
		rounding: 0,
		code: "YER",
		namePlural: "Yemeni rials",
	},
	{
		name: "South African Rand",
		symbol: "R",
		symbolNative: "R",
		minorUnits: 2,
		rounding: 0,
		code: "ZAR",
		namePlural: "South African rand",
	},
	{
		name: "Zambian Kwacha",
		symbol: "ZK",
		symbolNative: "ZK",
		minorUnits: 0,
		rounding: 0,
		code: "ZMK",
		namePlural: "Zambian kwachas",
	},
	{
		name: "Zimbabwean Dollar",
		symbol: "ZWL$",
		symbolNative: "ZWL$",
		minorUnits: 0,
		rounding: 0,
		code: "ZWL",
		namePlural: "Zimbabwean Dollar",
	},
];
